CREATE TABLE IF NOT EXISTS dominios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  landing_id INT NOT NULL,
  host VARCHAR(191) NOT NULL UNIQUE,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  creado_en DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (landing_id) REFERENCES landings(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
